version: "3"
services:

  ############# External services

  memcached:
    image: memcached:1.4.38
    restart: unless-stopped

  mongodb:
    image: mongo:3.2.16
    # Use WiredTiger in all environments, just like at edx.org
    command: mongod --smallfiles --nojournal --storageEngine wiredTiger
    restart: unless-stopped

  lms:
    image: eoluchile/edx-platform:ironwood
    volumes:
      - ../:/openedx/requirements/eol_completion
    depends_on:
      - memcached
      - mongodb